import { StyleSheet } from 'react-native';
import { COLORS } from '../colors';

export const containers = StyleSheet.create({
  containerRegisterForm: {
    alignContent: 'center',
    alignSelf: 'center',
    flexDirection: 'column',
  },
});

export const formRegister = StyleSheet.create({
  inputUserName: {
    fontSize: 20,
    color: COLORS.GRAY,
    marginTop: 10,
    marginBottom: 5,
    fontWeight: 'bold',
    fontFamily: 'Nunito_500Medium',
    borderColor: COLORS.WHITE,
    backgroundColor: COLORS.WHITE,
    borderWidth: 1,
    width: 330,
    height: 45,
    padding: 10,
    fontSize: 13,
    fontWeight: '300',
    marginBottom: 10,
    borderRadius: 8,
    bottom: 15,
  },
  inputEmail: {
    fontSize: 20,
    color: COLORS.GRAY,
    marginTop: 10,
    marginBottom: 5,
    fontWeight: 'bold',
    fontFamily: 'Nunito_500Medium',
    borderColor: COLORS.WHITE,
    backgroundColor: COLORS.WHITE,
    borderWidth: 1,
    width: 330,
    height: 45,
    padding: 10,
    fontSize: 13,
    fontWeight: '300',
    marginBottom: 10,
    borderRadius: 8,
  },
  inputPassword: {
    fontSize: 20,
    color: COLORS.GRAY,
    marginTop: 10,
    marginBottom: 5,
    fontWeight: 'bold',
    fontFamily: 'Nunito_500Medium',
    borderColor: COLORS.WHITE,
    backgroundColor: COLORS.WHITE,
    borderWidth: 1,
    width: 330,
    height: 45,
    padding: 10,
    fontSize: 13,
    fontWeight: '300',
    marginBottom: 10,
    borderRadius: 8,
    top: 15,
  },
  buttonContainer: {
    backgroundColor: COLORS.LIGHT_PURPLE,
    borderRadius: 20,
    width: 150,
    height: 40,
    alignContent: 'center',
    alignSelf: 'center',
    top: 25,
  },
  buttonText: {
    color: COLORS.WHITE,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: 'Poppins_500Medium',
    fontWeight: '600',
    fontSize: 16,
    top: 8,
  },
  askText: {
    top: 40,
    alignContent: 'center',
    alignSelf: 'center',
    fontFamily: 'Nunito_500Medium',
    color: COLORS.WHITE,
  },
  hyperlink: {
    top: 40,
    alignContent: 'center',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontFamily: 'Nunito_500Medium',
    color: COLORS.WHITE,
  },
});
